name: Generate timetable


on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate timetable.json
        run: python main.py
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1f
          files: sched.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
